-- ============================================================================
-- POWER BI REUSABLE DAX MEASURES LIBRARY
-- File: powerbi/dax_library.dax
-- Purpose: Enterprise calculation rules for Nifty 100 Analytics
-- ============================================================================

-- 5.1 Revenue & Growth Measures
Total Revenue = SUM(fact_profit_loss[sales])
Total Net Profit = SUM(fact_profit_loss[net_profit])
Avg OPM % = AVERAGE(fact_profit_loss[opm_pct])

Revenue YoY Growth % = 
VAR CurrentYear = CALCULATE(SUM(fact_profit_loss[sales]))
VAR PreviousYear = CALCULATE(SUM(fact_profit_loss[sales]), DATEADD(dim_year[year_date], -1, YEAR))
RETURN
IF(NOT ISBLANK(PreviousYear) && PreviousYear <> 0, DIVIDE(CurrentYear - PreviousYear, PreviousYear) * 100, BLANK())

3Y Sales CAGR % = CALCULATE(AVERAGE(fact_analysis[value_pct]), fact_analysis[period_label] = "3Y", fact_analysis[metric] = "compounded_sales_growth")
5Y Sales CAGR % = CALCULATE(AVERAGE(fact_analysis[value_pct]), fact_analysis[period_label] = "5Y", fact_analysis[metric] = "compounded_sales_growth")

-- 5.2 Profitability & Structural Performance
Net Profit Margin % = DIVIDE(SUM(fact_profit_loss[net_profit]), SUM(fact_profit_loss[sales])) * 100
Avg ROE % = AVERAGE(dim_company[roe_percentage])
ROE Last Year = CALCULATE(AVERAGE(fact_analysis[value_pct]), fact_analysis[period_label] = "Last Year", fact_analysis[metric] = "roe")
Interest Coverage Ratio = DIVIDE(SUM(fact_profit_loss[operating_profit]), SUM(fact_profit_loss[interest]))

-- 5.3 Balance Sheet & Credit Risk Leverage
Avg Debt to Equity = AVERAGE(fact_balance_sheet[debt_to_equity])
Latest Debt to Equity = CALCULATE(AVERAGE(fact_balance_sheet[debt_to_equity]), LASTDATE(dim_year[year_date]))
Total Borrowings = SUM(fact_balance_sheet[borrowings])
Debt Free Flag = IF([Latest Debt to Equity] < 0.1, "Debt Free", "Has Debt")

-- 5.4 Cash Flow Health
Free Cash Flow = SUM(fact_cash_flow[operating_activity]) + SUM(fact_cash_flow[investing_activity])
Cash Conversion Ratio = DIVIDE(SUM(fact_cash_flow[operating_activity]), SUM(fact_profit_loss[net_profit]))

-- 5.6 Machine Learning Health Indicators
Latest Health Score = CALCULATE(MAX(fact_ml_scores[overall_score]), LASTDATE(fact_ml_scores[computed_at]))

Health Label = 
SWITCH(
    TRUE(),
    [Latest Health Score] >= 85, "EXCELLENT",
    [Latest Health Score] >= 70, "GOOD",
    [Latest Health Score] >= 50, "AVERAGE",
    [Latest Health Score] >= 35, "WEAK",
    "POOR"
)

Health Score Color = 
SWITCH(
    [Health Label],
    "EXCELLENT", "#2ECC71",
    "GOOD", "#82E0AA",
    "AVERAGE", "#F7DC6F",
    "WEAK", "#F0A500",
    "POOR", "#E74C3C",
    "#CCCCCC"
)
